#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f ghostosint.key; then
  echo "Error: ghostosint.key already exists"
  exit 1
fi

if test -f ghostosint.crt; then
  echo "Error: ghostosint.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out ghostosint.crt -keyout ghostosint.key -subj "/CN=localhost"

chmod 600 ghostosint.crt
chmod 600 ghostosint.key
